language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.4.0
  - DJANGO_VERSION=1.5.0
  - DJANGO_VERSION=1.6.0
  - DJANGO_VERSION=1.7.0
  - DJANGO_VERSION=1.8.0
install:
  - pip install -q Django~=$DJANGO_VERSION
  - python setup.py -q install
script: python setup.py test
